# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quadrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('quadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.Quadrant')),
            ],
        ),
        migrations.AddField(
            model_name='matrix',
            name='q1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='q1', to='matrix.Quadrant'),
        ),
        migrations.AddField(
            model_name='matrix',
            name='q2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='q2', to='matrix.Quadrant'),
        ),
        migrations.AddField(
            model_name='matrix',
            name='q3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='q3', to='matrix.Quadrant'),
        ),
        migrations.AddField(
            model_name='matrix',
            name='q4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='q4', to='matrix.Quadrant'),
        ),
    ]
