# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesession',
            name='quadrant',
            field=models.CharField(choices=[('q1', 'q1'), ('q2', 'q2'), ('q3', 'q3'), ('q4', 'q4')], max_length=2),
        ),
    ]
