# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_auto_20170723_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesession',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
